#!/usr/bin/env python3
"""Synthesize the living project state Hermes auto-ingests.

This is the join point of the information flow. It reads:

  * the latest weekly report   (ops/reports/<week>.md),
  * recent meeting notes        (ops/meetings/<date>/notes.md),
  * recent meeting transcripts  (ops/meetings/<date>/transcript.md),
  * the previous project state   (ops/state/PROJECT_STATE.md),

and produces two artifacts:

  1. ops/state/PROJECT_STATE.md  — the full, human-readable living state.
  2. A managed block inside errorAnalysis/AGENTS.md (between markers) — a compact
     digest. Because Hermes auto-injects AGENTS.md every turn, updating that block
     is what makes the orchestration "just know" the latest project state.

Two synthesis modes
-------------------
* LLM mode (preferred): if an OpenAI-compatible endpoint is configured via env
  (STATE_LLM_API_KEY / OPENAI_API_KEY, optional STATE_LLM_BASE_URL +
  STATE_LLM_MODEL), the model deduplicates and rewrites the state intelligently.
* Extractive fallback (no key): deterministically assembles the state from the
  structured headings in each notes.md plus the latest report. Always available,
  zero dependencies, good enough to be useful.

Usage
-----
    python ops/synthesize_state.py                 # LLM if configured, else extractive
    python ops/synthesize_state.py --no-llm        # force extractive
    python ops/synthesize_state.py --meetings 5    # include last 5 meetings
    python ops/synthesize_state.py --dry-run       # print, don't write
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

OPS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = OPS_DIR.parent          # errorAnalysis/
REPORTS_DIR = OPS_DIR / "reports"
MEETINGS_DIR = OPS_DIR / "meetings"
STATE_DIR = OPS_DIR / "state"
STATE_FILE = STATE_DIR / "PROJECT_STATE.md"
AGENTS_FILE = PROJECT_ROOT / "AGENTS.md"

BLOCK_BEGIN = "<!-- BEGIN:PROJECT_STATE (auto-generated by ops/synthesize_state.py — do not edit by hand) -->"
BLOCK_END = "<!-- END:PROJECT_STATE -->"

NOTE_HEADINGS = [
    "Decisions made",
    "Feedback / critiques",
    "Ideas considered",
    "Action items",
    "Open questions",
]


# --------------------------------------------------------------------------- #
# Gathering inputs
# --------------------------------------------------------------------------- #
def latest_report() -> Path | None:
    reports = sorted(REPORTS_DIR.glob("*-W*.md"))
    return reports[-1] if reports else None


def meeting_dirs(limit: int) -> list[Path]:
    dirs = [
        d for d in MEETINGS_DIR.iterdir()
        if d.is_dir() and re.fullmatch(r"\d{4}-\d{2}-\d{2}", d.name)
    ]
    dirs.sort(key=lambda d: d.name)
    return dirs[-limit:] if limit > 0 else dirs


def parse_sections(md_text: str) -> dict[str, list[str]]:
    """Split a notes.md into {heading: [bullet lines]} for known headings."""
    sections: dict[str, list[str]] = {h: [] for h in NOTE_HEADINGS}
    current: str | None = None
    for raw in md_text.splitlines():
        line = raw.rstrip()
        if line.startswith("## "):
            title = line[3:].strip()
            current = title if title in sections else None
            continue
        if current is None:
            continue
        stripped = line.lstrip()
        if stripped.startswith(("- ", "* ", "- [")):
            content = stripped[2:].strip()
            if content and not content.startswith("<!--"):
                sections[current].append(content)
    return sections


# --------------------------------------------------------------------------- #
# Extractive (no-LLM) synthesis
# --------------------------------------------------------------------------- #
def render_report_digest(report_path: Path | None) -> list[str]:
    if not report_path:
        return ["_No weekly report found. Run `python ops/weekly_report.py`._"]
    lines = report_path.read_text(errors="replace").splitlines()
    glance: list[str] = []
    capture = False
    for line in lines:
        if line.startswith("## At a glance"):
            capture = True
            continue
        if capture:
            if line.startswith("## "):
                break
            if line.strip().startswith("-"):
                glance.append(line.strip())
    digest = [f"From **{report_path.name}**:"]
    digest.extend(glance or ["_(report had no 'At a glance' section)_"])
    return digest


def extractive_state(report_path: Path | None, meetings: list[Path], today: dt.date) -> str:
    L: list[str] = []
    L.append("# Project state (living document)")
    L.append("")
    L.append(f"> Auto-synthesized on {today.isoformat()} by `ops/synthesize_state.py` "
             "(extractive mode). The compact digest also lives in `AGENTS.md` so Hermes "
             "loads it every turn. Edit upstream sources (meeting `notes.md`, weekly "
             "reports), not this file — it is regenerated.")
    L.append("")

    last_meeting = meetings[-1].name if meetings else "—"
    L.append("## Current snapshot")
    L.append("")
    L.append(f"- **As of:** {today.isoformat()}")
    L.append(f"- **Most recent meeting:** {last_meeting}")
    L.append(f"- **Meetings folded in:** {', '.join(m.name for m in meetings) or '—'}")
    L.append("")

    L.append("## Recent progress (from the latest weekly report)")
    L.append("")
    L.extend(render_report_digest(report_path))
    L.append("")

    # Aggregate structured notes across meetings, newest first, with provenance.
    agg: dict[str, list[tuple[str, str]]] = {h: [] for h in NOTE_HEADINGS}
    for d in reversed(meetings):
        notes = d / "notes.md"
        if not notes.exists():
            continue
        sections = parse_sections(notes.read_text(errors="replace"))
        for h in NOTE_HEADINGS:
            for item in sections[h]:
                agg[h].append((d.name, item))

    heading_titles = {
        "Decisions made": "Decisions (cumulative)",
        "Feedback / critiques": "Open feedback & critiques",
        "Ideas considered": "Ideas on the table",
        "Action items": "Action items",
        "Open questions": "Open questions",
    }
    for h in NOTE_HEADINGS:
        L.append(f"## {heading_titles[h]}")
        L.append("")
        items = agg[h]
        if not items:
            L.append("_None recorded yet._")
        else:
            for date_str, item in items:
                L.append(f"- {item}  _( {date_str} )_")
        L.append("")

    return "\n".join(L)


# --------------------------------------------------------------------------- #
# LLM synthesis (OpenAI-compatible, stdlib only)
# --------------------------------------------------------------------------- #
def llm_config() -> dict | None:
    key = os.environ.get("STATE_LLM_API_KEY") or os.environ.get("OPENAI_API_KEY")
    if not key:
        return None
    return {
        "key": key,
        "base_url": os.environ.get("STATE_LLM_BASE_URL", "https://api.openai.com/v1").rstrip("/"),
        "model": os.environ.get("STATE_LLM_MODEL", "gpt-4o-mini"),
    }


def llm_synthesize(cfg: dict, prompt: str) -> str:
    url = f"{cfg['base_url']}/chat/completions"
    payload = {
        "model": cfg["model"],
        "temperature": 0.2,
        "messages": [
            {"role": "system", "content": _LLM_SYSTEM},
            {"role": "user", "content": prompt},
        ],
    }
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode(),
        headers={
            "Authorization": f"Bearer {cfg['key']}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=180) as resp:
        data = json.loads(resp.read())
    return data["choices"][0]["message"]["content"].strip()


_LLM_SYSTEM = (
    "You maintain the living PROJECT_STATE.md for a computer-use-agent (CUA) "
    "failure-analysis research project orchestrated by an agent named Hermes. "
    "Given the previous state, the latest auto-generated weekly report, and recent "
    "meeting notes/transcripts, produce an updated PROJECT_STATE.md. Requirements:\n"
    "- Deduplicate and merge; carry forward still-relevant facts, drop resolved ones.\n"
    "- Be concise and factual; mark anything provisional.\n"
    "- Keep these H2 sections in order: Current snapshot, Recent progress, "
    "Decisions, Open feedback & critiques, Ideas on the table, Action items, "
    "Open questions.\n"
    "- Action items as GitHub task list items with owners when known.\n"
    "- Output ONLY the Markdown for PROJECT_STATE.md, starting with '# Project state'."
)


def build_llm_prompt(prev_state: str, report_path: Path | None, meetings: list[Path]) -> str:
    parts = ["## Previous PROJECT_STATE.md", prev_state or "(none yet)", ""]
    if report_path:
        parts += [f"## Latest weekly report ({report_path.name})",
                  report_path.read_text(errors="replace"), ""]
    for d in meetings:
        notes = d / "notes.md"
        transcript = d / "transcript.md"
        parts.append(f"## Meeting {d.name} — notes.md")
        parts.append(notes.read_text(errors="replace") if notes.exists() else "(no notes.md)")
        parts.append("")
        if transcript.exists():
            t = transcript.read_text(errors="replace")
            # Cap transcript size to keep the request bounded.
            if len(t) > 20000:
                t = t[:20000] + "\n…(truncated)…"
            parts.append(f"## Meeting {d.name} — transcript.md (verbatim, may be noisy)")
            parts.append(t)
            parts.append("")
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# AGENTS.md managed block
# --------------------------------------------------------------------------- #
def build_agents_block(state_md: str, today: dt.date, meetings: list[Path]) -> str:
    """Compact digest injected into AGENTS.md (what Hermes reads every turn)."""
    last_meeting = meetings[-1].name if meetings else "—"

    def section(title: str, limit: int) -> list[str]:
        out: list[str] = []
        capture = False
        count = 0
        for line in state_md.splitlines():
            if line.startswith("## "):
                capture = line[3:].strip().lower().startswith(title.lower())
                continue
            if capture and line.strip().startswith(("-", "*")) and count < limit:
                out.append(line.strip())
                count += 1
        return out

    L = [BLOCK_BEGIN]
    L.append("## Live project state")
    L.append("")
    L.append(f"_As of {today.isoformat()}; last meeting {last_meeting}. "
             "Full detail in `ops/state/PROJECT_STATE.md`. Regenerated by "
             "`ops/synthesize_state.py`; do not edit this block by hand._")
    L.append("")
    for title in ("Recent progress", "Decisions", "Action items", "Open questions"):
        items = section(title, 6)
        if not items:
            continue
        L.append(f"**{title}:**")
        L.extend(items)
        L.append("")
    L.append(BLOCK_END)
    return "\n".join(L).rstrip()


def update_agents_block(block: str) -> None:
    text = AGENTS_FILE.read_text()
    if BLOCK_BEGIN in text and BLOCK_END in text:
        pattern = re.compile(
            re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END),
            re.DOTALL,
        )
        new_text = pattern.sub(block, text)
    else:
        new_text = text.rstrip() + "\n\n" + block + "\n"
    AGENTS_FILE.write_text(new_text)


# --------------------------------------------------------------------------- #
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--meetings", type=int, default=3, help="how many recent meetings to fold in")
    ap.add_argument("--no-llm", action="store_true", help="force extractive mode")
    ap.add_argument("--dry-run", action="store_true", help="print results, do not write files")
    args = ap.parse_args()

    today = dt.date.today()
    report = latest_report()
    meetings = meeting_dirs(args.meetings)
    prev_state = STATE_FILE.read_text(errors="replace") if STATE_FILE.exists() else ""

    cfg = None if args.no_llm else llm_config()
    if cfg:
        print(f"Synthesizing with LLM ({cfg['model']} @ {cfg['base_url']})…", file=sys.stderr)
        try:
            state_md = llm_synthesize(cfg, build_llm_prompt(prev_state, report, meetings))
        except (urllib.error.URLError, urllib.error.HTTPError, KeyError, TimeoutError) as e:
            print(f"LLM synthesis failed ({e}); falling back to extractive.", file=sys.stderr)
            state_md = extractive_state(report, meetings, today)
    else:
        print("Synthesizing in extractive mode (no LLM endpoint configured).", file=sys.stderr)
        state_md = extractive_state(report, meetings, today)

    block = build_agents_block(state_md, today, meetings)

    if args.dry_run:
        print("===== PROJECT_STATE.md =====\n")
        print(state_md)
        print("\n===== AGENTS.md block =====\n")
        print(block)
        return 0

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(state_md.rstrip() + "\n")
    print(f"Wrote {STATE_FILE}", file=sys.stderr)
    update_agents_block(block)
    print(f"Updated managed block in {AGENTS_FILE}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
