#!/usr/bin/env python3
"""Synthesize the living project state Hermes auto-ingests.

This is the join point of the information flow. It reads:

  * the latest weekly report   (ops/reports/<week>.md),
  * the most recent meeting notes (default: last 1 date folder under ops/meetings/),
  * optional supplements        (notes.md, wispr_supplement.md, transcript.md),
  * the previous project state   (ops/state/PROJECT_STATE.md),

and produces two artifacts:

  1. ops/state/PROJECT_STATE.md  — the full, human-readable living state.
  2. A managed block inside the repo-root `AGENTS.md` (between markers) — a compact
     digest. Hermes walks to the git root and auto-injects that file every turn.

Two synthesis modes
-------------------
* LLM mode (preferred): Anthropic by default (`ANTHROPIC_API_KEY` in env or
  `ops/config/meetings.env`). Optional OpenAI-compatible via `STATE_LLM_PROVIDER=openai`.
* Extractive fallback (no key): deterministic merge from structured headings.

Before synthesis, optionally runs `format_meeting_notes.py` logic on any meeting
that has `gdoc_notes.md` but no `notes.md` (use `--skip-format` to disable).

Usage
-----
    python ops/format_meeting_notes.py --date 2026-06-24   # structure raw gdoc first
    python ops/synthesize_state.py                       # LLM if Anthropic key set
    python ops/synthesize_state.py --no-llm              # force extractive
    python ops/synthesize_state.py --skip-format         # do not auto-format gdocs
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

_OPS = Path(__file__).resolve().parent
if str(_OPS) not in sys.path:
    sys.path.insert(0, str(_OPS))

from llm_client import complete, llm_config
from format_meeting_notes import format_meeting
OPS_DIR = _OPS
REPO_ROOT = OPS_DIR.parent          # pixelAgent/ (git root)
REPORTS_DIR = OPS_DIR / "reports"
MEETINGS_DIR = OPS_DIR / "meetings"
STATE_DIR = OPS_DIR / "state"
STATE_FILE = STATE_DIR / "PROJECT_STATE.md"
AGENTS_FILE = REPO_ROOT / "AGENTS.md"

BLOCK_BEGIN = "<!-- BEGIN:PROJECT_STATE (auto-generated by ops/synthesize_state.py — do not edit by hand) -->"
BLOCK_END = "<!-- END:PROJECT_STATE -->"

NOTE_HEADINGS = [
    "Decisions made",
    "Feedback / critiques",
    "Ideas considered",
    "Action items",
    "Open questions",
    "Technologies discussed",
    "Ideas & research directions",
]


def meeting_artifacts(d: Path) -> dict[str, Path]:
    """Return available meeting files for a date folder."""
    out: dict[str, Path] = {}
    for name in ("gdoc_notes.md", "notes.md", "wispr_supplement.md", "transcript.md"):
        p = d / name
        if p.exists():
            out[name.removesuffix(".md")] = p
    return out


def note_sources_for_parsing(d: Path) -> list[Path]:
    """Structured notes first (LLM-formatted), then raw gdoc."""
    arts = meeting_artifacts(d)
    order = ["notes", "gdoc_notes"]
    return [arts[k] for k in order if k in arts]


# --------------------------------------------------------------------------- #
# Gathering inputs
# --------------------------------------------------------------------------- #
def latest_report() -> Path | None:
    reports = sorted(REPORTS_DIR.glob("*-W*.md"))
    return reports[-1] if reports else None


def meeting_dirs(limit: int) -> list[Path]:
    dirs = [
        d for d in MEETINGS_DIR.iterdir()
        if d.is_dir() and re.fullmatch(r"\d{4}-\d{2}-\d{2}", d.name)
    ]
    dirs.sort(key=lambda d: d.name)
    return dirs[-limit:] if limit > 0 else dirs


def parse_sections(md_text: str) -> dict[str, list[str]]:
    """Split a notes.md into {heading: [bullet lines]} for known headings."""
    sections: dict[str, list[str]] = {h: [] for h in NOTE_HEADINGS}
    current: str | None = None
    for raw in md_text.splitlines():
        line = raw.rstrip()
        if line.startswith("## "):
            title = line[3:].strip()
            current = title if title in sections else None
            continue
        if current is None:
            continue
        stripped = line.lstrip()
        if stripped.startswith(("- ", "* ", "- [")):
            content = stripped[2:].strip()
            if content and not content.startswith("<!--"):
                sections[current].append(content)
    return sections


# --------------------------------------------------------------------------- #
# Extractive (no-LLM) synthesis
# --------------------------------------------------------------------------- #
def render_report_digest(report_path: Path | None) -> list[str]:
    if not report_path:
        return ["_No weekly report found. Run `python ops/weekly_report.py`._"]
    lines = report_path.read_text(errors="replace").splitlines()
    glance: list[str] = []
    capture = False
    for line in lines:
        if line.startswith("## At a glance"):
            capture = True
            continue
        if capture:
            if line.startswith("## "):
                break
            if line.strip().startswith("-"):
                glance.append(line.strip())
    digest = [f"From **{report_path.name}**:"]
    digest.extend(glance or ["_(report had no 'At a glance' section)_"])
    return digest


def extractive_state(report_path: Path | None, meetings: list[Path], today: dt.date) -> str:
    L: list[str] = []
    L.append("# Project state (living document)")
    L.append("")
    L.append(f"> Auto-synthesized on {today.isoformat()} by `ops/synthesize_state.py` "
             "(extractive mode). The compact digest also lives in `AGENTS.md` so Hermes "
             "loads it every turn. Edit upstream sources (meeting notes in "
             "`ops/meetings/`, weekly reports in `ops/reports/`), not this file "
             "— it is regenerated.")
    L.append("")

    last_meeting = meetings[-1].name if meetings else "—"
    L.append("## Current snapshot")
    L.append("")
    L.append(f"- **As of:** {today.isoformat()}")
    L.append(f"- **Most recent meeting:** {last_meeting}")
    L.append(f"- **Meetings folded in:** {', '.join(m.name for m in meetings) or '—'}")
    L.append("")

    L.append("## Recent progress (from the latest weekly report)")
    L.append("")
    L.extend(render_report_digest(report_path))
    L.append("")

    # Aggregate structured notes across meetings, newest first, with provenance.
    agg: dict[str, list[tuple[str, str]]] = {h: [] for h in NOTE_HEADINGS}
    gdoc_excerpts: list[tuple[str, str]] = []
    for d in reversed(meetings):
        primary = note_sources_for_parsing(d)
        if primary:
            sections = parse_sections(primary[0].read_text(errors="replace"))
            for h in NOTE_HEADINGS:
                for item in sections[h]:
                    agg[h].append((d.name, item))
        arts = meeting_artifacts(d)
        if "gdoc_notes" in arts and (not primary or primary[0].name == "gdoc_notes.md") and not any(
            parse_sections(arts["gdoc_notes"].read_text(errors="replace"))[h]
            for h in NOTE_HEADINGS
        ):
            text = arts["gdoc_notes"].read_text(errors="replace")
            # Strip header boilerplate for excerpt
            body = re.sub(r"^#.*?\n\n>", "", text, count=1, flags=re.S)
            body = re.sub(r"^>.*\n", "", body, flags=re.M).strip()
            if body:
                excerpt = body[:1200] + ("…" if len(body) > 1200 else "")
                gdoc_excerpts.append((d.name, excerpt))

    heading_titles = {
        "Decisions made": "Decisions (cumulative)",
        "Feedback / critiques": "Open feedback & critiques",
        "Ideas considered": "Ideas on the table",
        "Action items": "Action items",
        "Open questions": "Open questions",
        "Technologies discussed": "Technologies & tools discussed",
        "Ideas & research directions": "Research directions",
    }
    for h in NOTE_HEADINGS:
        L.append(f"## {heading_titles[h]}")
        L.append("")
        items = agg[h]
        if not items:
            L.append("_None recorded yet._")
        else:
            for date_str, item in items:
                L.append(f"- {item}  _( {date_str} )_")
        L.append("")

    if gdoc_excerpts:
        L.append("## Meeting notes (Google Doc excerpts)")
        L.append("")
        for date_str, excerpt in gdoc_excerpts:
            L.append(f"### {date_str}")
            L.append("")
            L.append(excerpt)
            L.append("")

    return "\n".join(L)


# --------------------------------------------------------------------------- #
# LLM synthesis (Anthropic default via llm_client)
# --------------------------------------------------------------------------- #
_LLM_SYSTEM = (
    "You maintain the living PROJECT_STATE.md for a computer-use-agent (CUA) "
    "research program (pixelAgent) orchestrated by an agent named Hermes. "
    "Given the previous PROJECT_STATE.md (cumulative memory), the latest "
    "auto-generated weekly report, and notes from the most recent meeting only, "
    "produce an updated PROJECT_STATE.md. Requirements:\n"
    "- Incremental merge: add new facts from this meeting; update or remove items "
    "that are outdated or completed; carry forward still-relevant facts from "
    "previous state.\n"
    "- Deduplicate; do not repeat the same bullet in multiple sections.\n"
    "- Be concise and factual; mark anything provisional.\n"
    "- Keep these H2 sections in order: Current snapshot, Recent progress, "
    "Decisions, Open feedback & critiques, Ideas on the table, Action items, "
    "Open questions, Technologies & tools discussed.\n"
    "- Action items as GitHub task list items with owners when known; remove "
    "completed items unless still worth tracking.\n"
    "- Output ONLY the Markdown for PROJECT_STATE.md, starting with '# Project state'."
)


def llm_synthesize(cfg: dict, prompt: str) -> str:
    return complete(cfg, _LLM_SYSTEM, prompt, max_tokens=8192)


def maybe_format_gdoc_meetings(meetings: list[Path], cfg: dict, *, force: bool = False) -> None:
    for d in meetings:
        arts = meeting_artifacts(d)
        if "gdoc_notes" not in arts:
            continue
        if "notes" in arts and not force:
            continue
        format_meeting(d, cfg, force=force)


def build_llm_prompt(prev_state: str, report_path: Path | None, meetings: list[Path]) -> str:
    parts = ["## Previous PROJECT_STATE.md", prev_state or "(none yet)", ""]
    if report_path:
        parts += [f"## Latest weekly report ({report_path.name})",
                  report_path.read_text(errors="replace"), ""]
    for d in meetings:
        arts = meeting_artifacts(d)
        for key, label in (
            ("notes", "structured meeting notes (preferred)"),
            ("gdoc_notes", "Google Doc notes (raw)"),
            ("wispr_supplement", "Wispr Flow supplement"),
            ("transcript", "transcript (verbatim, may be noisy)"),
        ):
            if key not in arts:
                continue
            t = arts[key].read_text(errors="replace")
            if key == "transcript" and len(t) > 20000:
                t = t[:20000] + "\n…(truncated)…"
            parts.append(f"## Meeting {d.name} — {label}")
            parts.append(t)
            parts.append("")
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# AGENTS.md managed block
# --------------------------------------------------------------------------- #
def build_agents_block(state_md: str, today: dt.date, meetings: list[Path]) -> str:
    """Compact digest injected into AGENTS.md (what Hermes reads every turn)."""
    last_meeting = meetings[-1].name if meetings else "—"

    def section(title: str, limit: int) -> list[str]:
        out: list[str] = []
        capture = False
        count = 0
        for line in state_md.splitlines():
            if line.startswith("## "):
                capture = line[3:].strip().lower().startswith(title.lower())
                continue
            if capture and line.strip().startswith(("-", "*")) and count < limit:
                out.append(line.strip())
                count += 1
        return out

    L = [BLOCK_BEGIN]
    L.append("## Live project state")
    L.append("")
    L.append(f"_As of {today.isoformat()}; last meeting {last_meeting}. "
             "Full detail in `ops/state/PROJECT_STATE.md`. Regenerated by "
             "`ops/synthesize_state.py`; do not edit this block by hand._")
    L.append("")
    for title in ("Recent progress", "Decisions", "Action items", "Open questions"):
        items = section(title, 6)
        if not items:
            continue
        L.append(f"**{title}:**")
        L.extend(items)
        L.append("")
    L.append(BLOCK_END)
    return "\n".join(L).rstrip()


def update_agents_block(block: str) -> None:
    text = AGENTS_FILE.read_text()
    if BLOCK_BEGIN in text and BLOCK_END in text:
        pattern = re.compile(
            re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END),
            re.DOTALL,
        )
        new_text = pattern.sub(block, text)
    else:
        new_text = text.rstrip() + "\n\n" + block + "\n"
    AGENTS_FILE.write_text(new_text)


# --------------------------------------------------------------------------- #
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--meetings",
        type=int,
        default=1,
        help="how many recent meeting folders to read as input (default 1; merges into "
        "previous PROJECT_STATE.md in LLM mode)",
    )
    ap.add_argument("--no-llm", action="store_true", help="force extractive mode")
    ap.add_argument("--skip-format", action="store_true", help="do not auto-format gdoc → notes.md")
    ap.add_argument("--format-only", action="store_true", help="only format gdoc notes, then exit")
    ap.add_argument("--force-format", action="store_true", help="re-format even if notes.md exists")
    ap.add_argument("--dry-run", action="store_true", help="print results, do not write files")
    args = ap.parse_args()

    today = dt.date.today()
    report = latest_report()
    meetings = meeting_dirs(args.meetings)
    prev_state = STATE_FILE.read_text(errors="replace") if STATE_FILE.exists() else ""

    cfg = None if args.no_llm else llm_config()
    if cfg and not args.skip_format:
        print("Formatting raw Google Doc notes where needed…", file=sys.stderr)
        maybe_format_gdoc_meetings(meetings, cfg, force=args.force_format)

    if args.format_only:
        if not cfg:
            print("format-only requires ANTHROPIC_API_KEY (or LLM config).", file=sys.stderr)
            return 2
        return 0

    if cfg:
        print(
            f"Synthesizing with {cfg['provider']} ({cfg['model']})…",
            file=sys.stderr,
        )
        try:
            state_md = llm_synthesize(cfg, build_llm_prompt(prev_state, report, meetings))
        except Exception as e:
            print(f"LLM synthesis failed ({e}); falling back to extractive.", file=sys.stderr)
            state_md = extractive_state(report, meetings, today)
    else:
        print("Synthesizing in extractive mode (no LLM endpoint configured).", file=sys.stderr)
        state_md = extractive_state(report, meetings, today)

    block = build_agents_block(state_md, today, meetings)

    if args.dry_run:
        print("===== PROJECT_STATE.md =====\n")
        print(state_md)
        print("\n===== AGENTS.md block =====\n")
        print(block)
        return 0

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(state_md.rstrip() + "\n")
    print(f"Wrote {STATE_FILE}", file=sys.stderr)
    update_agents_block(block)
    print(f"Updated managed block in {AGENTS_FILE}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
